### ISSUE TITLE
ks 0.10.2 can not set parameter with underscore when '--env' option presented

### ISSUE THREAD

**Issue by everpeace** [ksonnet/ksonnet#554] opened 2018-05-23 02:34 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

- case 1: with `--env` option
  - `ks param set --env=default guestbook-ui nounderscore "a,b,c"` --> success
  - `ks param set --env=default guestbook-ui under_score "a,b,c"` --> __fail with 'invalid field name'__
- case 2: without `--env` opiton
  - `ks param set guestbook-ui nounderscore "a,b,c"` --> success
  - `ks param set guestbook-ui under_score "a,b,c"` --> success

**What you expected to happen**:
every command mentioned above all succeeded.

**How to reproduce it (as minimally and precisely as possible)**:
```
$ ks version
ksonnet version: 0.10.2
jsonnet version: v0.10.0
client-go version: 1.8

$ ks init ks-0.10.2-test
INFO Using context "minikube" from kubeconfig file "/Users/everpeace/.kube/config"
INFO Creating environment "default" with namespace "kube-system", pointing to cluster at address "https://192.168.99.100:8443"
INFO Generating ksonnet-lib data at path '/Users/everpeace/tmp/ks-0.10.2-test/lib/v1.8.0'

$ cd ks-0.10.2-test

# create a smple component from https://ksonnet.io/docs/tutorial
$  ks generate deployed-service guestbook-ui \
>    --image gcr.io/heptio-images/ks-guestbook-demo:0.1 \
>    --type ClusterIP
INFO Writing component at '/Users/everpeace/tmp/ks-0.10.2-test/components/guestbook-ui.jsonnet'

# CASE1:  with `--env` option ==> paremeters with underscore cannot be set....
$ ks param set --env=default guestbook-ui nounderscore "a,b,c"
INFO setting environment component                 component-name=guestbook-ui

$ ks param set --env=default guestbook-ui under_score "a,b,c"
INFO setting environment component                 component-name=guestbook-ui
ERROR set params: invalid field name "under_score"

# CASE2: without `--env` option ==> both parameters can be set.
$ ks param set guestbook-ui nounderscore "a,b,c"

$ ks param set guestbook-ui under_score "a,b,c"
```

**Anything else we need to know?**:
none.

**Environment**:
- ksonnet version (use `ks version`): 0.10.2
- Kubernetes version (use `kubectl version`): any version

**Comment by jlewi** [comment] 2018-05-23 04:55
Duplicate of #504 

I tried fixing the regex in ksonnet-lib per the comment in #504 and I was able to get Kubeflow workflows to work. PR coming

/close

**Closed** 2018-05-29 14:17 UTC
Labels: bug, p1 - Important
