### ISSUE TITLE
ks 0.10.1 does not show components named with underscore symbol

### ISSUE THREAD

**Issue by kozhukalov** [ksonnet/ksonnet#504] opened 2018-05-03 13:01 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
>
> /kind feature

**What happened**:
If a component file name has underscore symbol (e.g. some_component.jsonnet) then the command
```
ks show default -c some_component
```
fails with the error  
```
ERROR find objects: invalid field name "some_component"
```
**What you expected to happen**:
It must show the rendered component (0.9.2 works with such file names).

**How to reproduce it (as minimally and precisely as possible)**:
Create a component named some_component.jsonnet and put it to components directory and then run the `ks show default -c some_component` command.

**Anything else we need to know?**:

**Environment**:
- ksonnet version (use `ks version`):
ksonnet version: 0.10.1
jsonnet version: v0.10.0
client-go version: 1.8

- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.2", GitCommit:"bdaeafa71f6c7c04636251031f93464384d54963", GitTreeState:"clean", BuildDate:"2017-10-24T19:48:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.7", GitCommit:"b30876a5539f09684ff9fde266fda10b37738c9c", GitTreeState:"clean", BuildDate:"2018-01-16T21:52:38Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

**Comment by jlewi** [comment] 2018-05-23 04:19
@bryanl Any update? I'm trying with 0.10.2 and I'm hitting a similar issue.

There's a semi related issue #304 about parameter names with underscores. 

Did something change w.r.t to the set of allowed names?

**Comment by jlewi** [comment] 2018-05-23 04:31
I think this is a Duplicate of #554.

It looks to me like the error is coming from [here](https://github.com/ksonnet/ksonnet-lib/blob/master/ksonnet-gen/astext/astext.go#L45) which is using the regexes

```
	reFieldStr = regexp.MustCompile(`^[A-Za-z]+[A-Za-z0-9\-]*$`)
	// reField matches a field id.
	reField = regexp.MustCompile(`^[A-Za-z]+[A-Za-z0-9]*$`)
```

It looks like the jsonnet [spec](https://jsonnet.org/ref/spec.html) allows underscores for ids. It uses the regex

```
[_a-zA-Z][_a-zA-Z0-9]*
```

So this looks like a simple bug to me in ksonnet.

**Closed** 2018-05-24 19:43 UTC
