### ISSUE TITLE
pkg -> prototype -> component hierarchy is unnecessary complicated

### ISSUE THREAD

**Issue by redbaron** [ksonnet/ksonnet#263] opened 2018-01-04 15:18 UTC
Current way of pulling packages, then specifying components by using prototypes from a package is confusing and I can't see what it buys comparing to a more direct approach where `app.yaml` specifies components directly.

Something along the lines would achieve same result in a single step AND would allow packages to be updated per component, which is not possible right now:

```
apiVersion: 0.0.1
kind: ksonnet.io/app
components:
  redis-app:
    gitVersion:  ....
    name: redis
    prototype: redis-stateless
    registry: incubator
registries:
  incubator:
    ...
    uri: github.com/ksonnet/parts/tree/master/incubator
```

this would create following structure:
```
components/
  redis-app.jsonnet
  redis-app/
    redis-stateless.jsonnet
    redis.libsonnet (and rest of the files from incubator/redis/)
```

where `redis-app.jsonnet` is:
```
import './redis-app/redis-stateless.jsonnet'
```

and `redis-app/redis-stateless.jsonnet` is rendered `redis-stateless` prototype as it is being rendered now (I believe comments are removed and `local params = ...` added).

This also solves https://github.com/ksonnet/ksonnet/issues/262 , because prototypes can now reference packages they are part of using relative paths:

```
local redis = import './redis.libsonnet'; 
```

**Comment by bryanl** [comment] 2018-01-05 02:48
If you specify components in `app.yaml`, what is the canonical source? Whats in `app.yaml`, or what's in the components directory? ksonnet projects should be long lived, so I'm curious if the extra step is a problem. Is this less work than running `ks generate ...`? Perhaps we are missing some sort of way to `init` a project with components?

**Comment by redbaron** [comment] 2018-01-05 03:51
components directory should be what `/vendor` directory is for Go projects is - just local checkout of a code originating elsewhere. Maybe moving `/components/redis-app/` to `/vendor/redis-app` makes a bit more scence, but path to store code is not that important.

What is important is that rights now there it is:
   1. inconvenient for users: to start using something one need to add registry, add package, use prototype.
   1. inconvenient for package authors: prototype path references libsonnet files at install location, these paths cannot be just relative paths,which makes pkg development harder, for instance jsonnet commandline tools can't be used without fiddling with search paths.
   1. rigid: it is possible to install 2 prototypes (becoming component) from a single package, then upgrade of such package can't be done independently for each prototype(component) as they refer to shared package inside /vendor dir
   1. it is too magical, no other system I can remember modifies dependency source code at install time! Why `ks generate` step is needed at all?

**Comment by hausdorff** [comment] 2018-01-08 19:35
More comments to come soon, but I've marked #262 as a duplicate of #68 and closing, just FYI.

**Comment by hausdorff** [comment] 2018-01-08 19:56
@redbaron Interesting view, thanks for sharing. Just so we're on the same page, let me recap why things are the way they are.

Each library is basically an unopinionated collection of API objects. Each prototype is basically a "flavored distribution" of those API objects. _e.g._, `redis-stateless`, `redis-stateful`, and so on. These are dumped in to `components/` because we encourage users to mold them to fit needs. (This is a conscious decision, and a reaction to the params.yaml of Helm charts, which can get out of control; for us, the params are meant to get you started.)

Now, it sounds to me like the problem you're describing is actually a workflow problem:

1. We could consider a streamlined `generate` that will automatically install the package the prototype depends on.
1. This is a known issue and will be solved in #68.
1. Actually they can, but it's not documented, and it's not convenient. Basically you `pkg add` a different version of the library with a different name, and then upgrade them one-at-a-time. We don't have a linker so these dependencies can co-exist side-by-side.
1. I believe this is fairly common in web frameworks (_e.g._, Rails).

**Comment by redbaron** [comment] 2018-01-09 10:53
>  These are dumped in to components/ because we encourage users to mold them to fit needs.

@hausdorff, this wont work in practice, as the moment  you edit those files, you'll loose upgrade path. Only way to keep in manageable I can think of is what many people including me are doing with helm: instead of providing more and more extension points in templates, just fork and amend chart to own needs. Upgade path is then just git pull of fresh version from upstream and resolving conflicts. So more primitive and painful approach official Helm is taking, leads to simple and efficient workflow because it is so painful to use "official" way. 

With  current ksonnet file layout one could use git submodules inside vendor dir, but submodules are too confusing in practice, only most git savvy devs are comfortable with them, I failed to get any reasonable adoption of workflows based on git submodules in two distinct companies, despite trying best to educate people and automate as much as possible.

Another alternative to have customisations, but not losing upgrade path is to use "git subtree" to "mount" a library git repo into directory under vendor/ , but `git subtree` is even more magical AND it looses new files in "upstream" repos - so it is a no go for any practical purposes.

Now, back to usability points:
  1. If generate is streamlined, in practice there going to be 1:1 mapping between components, prototype and (more often than not) package. Why keeping them separate?
  1. 👍 
  1. bundling whole pkg inside component would solve it without users even thinking about it. There is also nothing to document then :)
  1. there are many more examples which don't do it: go, cargo, maven/sbt/lein, npm, django apps, pip, rpm, deb, docker containers - it is fairly uncommon to pull dependency and unconditionally modify it.  Generation step also makes it harder to just checkout and use dependency, all for benefits which I personally fail to see.

**Comment by hausdorff** [comment] 2018-01-10 00:24
@redbaron Hmm, I think I'm starting to understand the disconnect. Prototypes are just meant to be an easy way to get started _using a library_. Kind of like code examples you can access from the CLI.

Does that cause things to make more sense to you?

**Comment by redbaron** [comment] 2018-01-10 15:30
> Kind of like code examples you can access from the CLI.

Maybe thats was the intent, but today they grow into something completely different. They are not treated as examples or quick snippets, they are presented to user as first class objects: dedicated `prototype` subcommand, special metadata DSL in form of //@tagged comments, whole tutorial and experience is structured around how to pull a desired prototype into your app in a form of component, not how to install library/package and start using it.

**Comment by hausdorff** [comment] 2018-01-10 17:51
Yep, in fact, we wanted them to be first-class objects. Basically the idea was to have discoverable, documented-by-default code examples for how to use libraries, that you can reach from the CLI or an editor. I think that's unlikely to change at this point, but if you think the presentation of these goals is the core issue, I think it's reasonable to think about how that could be improved.

**Comment by hausdorff** [comment] 2018-01-11 19:47
@redbaron Ok, so, turning this into a practical action item, it looks like we should consider docs changes.

@abiogenesis-now, @bryanl Summarizing, it sounds like the problem is that in the docs it is not clear that prototypes are meant to be discoverable, documented-by-default, code examples. I'm not sure what's on your plate but I think this feedback is correct and we should at least put it on the backlog. Do you have thoughts?

**Comment by abiogenesis-now** [comment] 2018-01-11 23:46
That makes sense---I'll look into either restructuring the tutorial or adding additional content so that people are clear that prototypes are just a way of getting started.

**Comment by redbaron** [comment] 2018-01-12 11:19
What is the role of `environment/base.libsonnet` which suggests that customizations common for all envs are meant to be done there? Of components are editable by users, there is no need for it.

**Comment by bryanl** [comment] 2018-01-26 18:55
@redbaron `environment/base.libsonnet` does seem superfluous. In https://github.com/ksonnet/ksonnet/pull/295, we're discussing a method for deprecation now.

**Comment by bryanl** [comment] 2018-09-10 20:28
closing due to age. Please open if you want to discuss more.

**Closed by bryanl** 2018-09-10 20:28 UTC
Labels: documentation, p2 - Long-term Important
