### ISSUE TITLE
`ks apply` can cause service nodeport to be reallocated

### ISSUE THREAD

**Issue by jbeda** [ksonnet/ksonnet#200] opened 2017-12-03 00:46 UTC
This is a critical bug that we'll want to fix ASAP.  Not sure we can get it done in time for KubeCon though.

To repro:
```
ks generate deployed-service guestbook-ui \
  --image gcr.io/heptio-images/ks-guestbook-demo:0.1 \
  --type NodePort
ks apply default
kubectl get services guestbook-ui -o yaml -o jsonpath='{.spec.ports[0].nodePort}' ; echo
ks apply default
kubectl get services guestbook-ui -o yaml -o jsonpath='{.spec.ports[0].nodePort}' ; echo
```

I get a different nodePort each time I run `ks apply default`.

What I suspect is going on here is that when we apply we slam things up regardless of the state that is already there.  This means that we do a PUT of a new version of the service with a blank nodePort.  This causes the server to allocate a new nodePort at initializer time.  See https://github.com/kubernetes/kubernetes/issues/23551 for details.

The answer here is, unfortunately, not an easy one.  In a similar situation `kubectl` uses [strategic merge patch](https://github.com/kubernetes/community/blob/master/contributors/devel/strategic-merge-patch.md) or the three way merge semantics implied by `kubectl apply`.  For both of these the implication to the server is "only overwrite the stuff that I'm specifying instead of resetting the entire resource.

Options for solving this:
1. Do a read/modify/write of the resource and merge in our stuff client side.  This means that we'll have to figure out a smart way to "apply" the most recent version of a resource to the version that is on the server.
2. Create a strategic merge patch for the server to do its apply.  The problem here is one of knowing the right "mergeKey" for lists so that items in the list can line up.  This is listed in the swagger but will require quite a bit of plumbing to get right.
3. Use the 3 way merge `kubectl apply` mechanism.  This includes putting an annotation on the resource during the first apply and then using that as a base to do a 3 way merge to figure out what you changed and what the server changed and what you want to update.  The problem is that this code is baked into kubectl.  [There is a proposal](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/cli/apply_refactor.md) to pull it out to be server side that isn't implemented yet.
4. Prototype/implement some alternate way to do this.  We probably don't have time to do this but I've proposed that we instead have a map in an annotation around what component owns what fields.  We'd give the user a warning if they are looking to update a field that they don't own.  This would probably require server changes now and we may be too late to make it happen.

There are other places where this will bite us -- specifically around number of replicas and horizontal pod autoscaling.  This is a deep rabbit hole that we'll have to spend some time on.  We may want to help move `kubectl` forward so we can reuse some of the code there.

**Comment by jbeda** [comment] 2017-12-03 00:47
It looks like it is possible to do option 2 above by reusing code from kubectl.  See how tiller does it here: https://github.com/kubernetes/helm/blob/04769b7c26109aabfc9c6b645b345d665b6bd0cd/pkg/kube/client.go#L439:21.

**Comment by ncdc** [comment] 2017-12-03 20:09
You don't have to pull in that code from kubectl if you don't want to. You can just create a strategic merge patch directly. See e.g. https://github.com/heptio/ark/blob/ee16aab37840ce4c8ada6396dffd89180e6e85da/pkg/cmd/cli/plugin/add.go#L128-L131. Let me know if you need more help here.

**Comment by abiogenesis-now** [comment] 2017-12-04 18:07
Ok---I am also going to update the tutorial, previously I was actually highlighting the fact that we didn't use 3-way merge (and instead some sort of garbage collection type thing) as one of the key differences between `kubectl apply` and `ks apply` 

(context: @hausdorff has a specific integration test because of a case where `kubectl apply` is unintuitive? @bryanl you might want to sync up about that)

**Comment by hausdorff** [comment] 2017-12-04 23:49
This is indeed a critical issue, and we will need to fix it, but that fix won't make it for KubeCon.

I can see the appeal of (3), but I personally would much rather see (1). If we decide we truly cannot spend the time to do this in what I will tongue-in-cheek describe as "the right way", I would support (3), provided that:

1. _We have a clear path in the medium term to transition all users away from it unless they specifically opt in_.
1. We clearly and purposefully decide how this change relates to the ostensibly-shared merge code in ksonnet/kubecfg. This change would be _strictly incompatible_ with their changes, so our options are either (a) modify ksonnet/kubecfg to do the same behavior (this would involve opening an issue there and discussing), or (b) break compat with ksonnet/kubecfg.

My (and, I think, Joe's) problem with (3) is that strategic merge exhibits behavior that I would describe as very unintuitive. The ksonnet project has already made some attempt to curate a list of such behaviors (see, _e.g._, my [test-int](https://github.com/hausdorff/ksonnet/tree/int-test) branch). One example is that an attempt to "rename" a container actually cause both the old and new version to run, because merges are keyed on the name, transparently to the user. Unless you specifically know all the merge keys for the entire API it's really hard to reason about how your change gets merged in.

Most worryingly to me is that I am convinced that this is not a problem of implementation. The problem statement seems impossibly hard: take two plain-old YAML fragments and automatically infer from that how to merge them together, completely automatically, and have the result always be what users expect. Even if you know a lot about the schema, it's hard to know what to do in general. We've decided that arrays of containers should be merged by name, but what about ports arrays, which have no name? Should we replace the old array, add to it, something else? You can see how this gets complex.

I'm not sure what our appetite for discussing here what a solution for (1) might look like, but I will say that the flavor of solution I am inclined to support would _at least_ patch over these rough edges (_e.g._, by collecting them in those tests and fixing them in our implementation), but also I personally would like to see our client expand as many of these generated fields as it can client-side (we can't generate `status` fields, but we can perhaps fill in stuff like `ClusterIP` at least most of the time). We already strongly recommend everyone check in their generated YAML anyway, and the added benefit of making this a first-class citizen that we use to make `apply` and the patch merging easier is that GC will also work much better. For example, when a user deletes a file locally, your next `apply` should actually delete that item. But because it's not a file anymore, the client doesn't know to delete it. So keeping a fully-expanded version of the app YAML around is something we'll eventually want to support anyway.

**Comment by bryanl** [comment] 2017-12-11 15:55
My vote is for what `kubectl` does. After review, it may not be the best technical solution, but it is the solution that matches expected behaviors. If we want to deviate from this, we should be working with the SIG-CLI folks instead of creating yet another way of doing things. (for better or for worse)

**Comment by ncdc** [comment] 2017-12-11 16:03
xref https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/kubernetes-sig-api-machinery/OxLyMNp8I6A/s_L6bToZAgAJ (SIG API Machinery discussion on server side apply)

**Comment by kstewart** [comment] 2017-12-11 21:57
@bryanl It is your call on the specific fix, but I approve of your suggestion. How much time do you think is required to get this properly addressed?

**Comment by abiogenesis-now** [comment] 2018-01-04 19:37
Someone else (reviewing the roadmap) linked to [kubectl apply --prune](https://github.com/kubernetes/kubernetes/issues/19805) and its [implementation](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/apply.go#L229). Dropping it here in case it's helpful.

**Comment by Raffo** [comment] 2018-04-20 08:30
I was looking into using ksonnet for one project of mine, but this high priority bug would currently be a showstopper for me. Any proposals to move forward as this has been open since ~4 months?

**Closed** 2018-05-23 16:42 UTC
Labels: bug, p0 - Hair On Fire
