### ISSUE TITLE
prototypes can't rely on a registry name, but they do

### ISSUE THREAD

**Issue by redbaron** [ksonnet/ksonnet#262] opened 2018-01-04 14:48 UTC
Users are free to import registries under whatever name they want. 

```
kind: ksonnet.io/app
libraries:
  redis:
    registry: not-incubator
registries:
  not-incubator:
    protocol: github
    uri: github.com/ksonnet/parts/tree/master/incubator
```

which would pull registry into `vendor/not-incubator`. 

Prototype in that registry use imports like following:

```
local redis = import 'incubator/redis/redis.libsonnet'; 
```

so that `incubator/` path is hardcoded to "cannonical" registry name, which is fragile and wont work if use choose to spcify registry under different name

**Comment by bryanl** [comment] 2018-01-05 02:55
I've distilled this down to a simple use case that we can fix:

1. generate new ks app
2. Change registry name to something else
3. run `ks pkg list`.  It'll error saying the registry name does not exist.

**Comment by redbaron** [comment] 2018-01-05 03:55
There is even simpler case: `ks registry add incubatorXYZ github.com/ksonnet/parts/tree/master/incubator` and try to use anything from that registry. Files in registry refer to `incubator/` which obviously breaks as packages from registry are added as `vendor/incubatorXYZ`. In other words, if user adds registry using a name which is different from name registry authors are using, then things break.

**Comment by hausdorff** [comment] 2018-01-08 19:34
This is actually a duplicate of #68. The specific fix is detailed [here](https://github.com/ksonnet/ksonnet/issues/68#issuecomment-342935054).

I'm going to mark as duplicate, close, and reference #68 from #263 to close the loop. @redbaron feel free to open the issue again if I've missed something and that issue does not cover an important part of your issue.

**Closed by hausdorff** 2018-01-08 19:34 UTC
Labels: bug, duplicate, p1 - Important
